version: master_{build}
clone_depth: 1

services:
- docker

environment:
  COMMAND: if [[ "${APPVEYOR_REPO_COMMIT_MESSAGE@Q}" == *"[ci debug]"* ]]; then export DEBUG_FLAGS="--enable-debug"; fi; if [[ "${APPVEYOR_REPO_COMMIT_MESSAGE@Q}" == *"[ci gdb]"* ]]; then apt-get update && apt-get -y install gdb && export CONSTRUCT="gdb --batch -ex r -ex bt --return-child-result --args construct"; else export CONSTRUCT="construct"; fi && rmdir -v deps/rocksdb && ln -sv /usr/src/rocksdb deps && ./autogen.sh && ./configure --enable-assert ${DEBUG_FLAGS} && make install && ${CONSTRUCT} -smoketest -debug localhost

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-build-gcc-9-amd64

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-build-gcc-12-amd64

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-full-build-clang-15-amd64

for:
-
  build_script:
    - docker run -v `pwd`:/build "${DOCKER_IMAGE}" /bin/bash -c "${COMMAND}"

matrix:
  fast_finish: true

notifications:
  - provider: Webhook
    url: http://zemos.net:8448/webhook
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
