version: master_{build}
clone_depth: 1

services:
- docker

environment:
  COMMAND: if [[ "${APPVEYOR_REPO_COMMIT_MESSAGE}" == *"[ci debug]"* ]]; then export DEBUG_FLAGS="--enable-debug"; fi && rmdir -v deps/rocksdb && ln -sv /usr/src/rocksdb deps && ./autogen.sh && ./configure --enable-assert ${DEBUG_FLAGS} && make install && construct -smoketest -debug localhost

  matrix:
#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-gcc-8

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-gcc-9

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-gcc-10

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-clang-9

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-clang-10

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-clang-11

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-20.04-clang-12

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-gcc-8

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-gcc-9

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-gcc-10

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-gcc-11

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-gcc-12

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-clang-10

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-clang-11

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-clang-12

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-clang-13

#   - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#     DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-base-clang-14

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      DOCKER_IMAGE: jevolk/construct:ubuntu-22.04-full-clang-14

for:
-
  build_script:
    - docker run -v `pwd`:/build "${DOCKER_IMAGE}" /bin/bash -c "${COMMAND}"

matrix:
  fast_finish: true

notifications:
  - provider: Webhook
    url: http://zemos.net:8448/webhook
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
